blog/urls.py
from django.urls import path
from . import views
# url命名空间
app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.article, name='article')
]

simple_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models

# Create your models here.
# 博文模型
class Article(models.Model):
    article_title = models.CharField(max_length=300)
    article_text = models.TextField(max_length=5000)
    create_time = models.DateTimeField()
    update_time = models.DateTimeField()

    def __str__(self):
        return self.article_text

blog/views.py
from django.shortcuts import render, HttpResponse,get_object_or_404
from .models import Article
from django.template import loader

# Create your views here.
def index(request):
    blog_list = Article.objects.order_by('-update_time')
    context = {'website_title': 'simple_blog','blog_list':blog_list}
    return render(request, 'index.html', context)

def article(request, article_id):
    # article = Article.objects.get(pk=article_id)
    article = get_object_or_404(Article, pk=article_id)
    context = {'website_title': 'simple_blog', 'article': article}
    return render(request, 'article.html', context)

blog/templates/article.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ website_title }}</title>
    <style>
        html,
        body,
        div,
        p {
            margin: 0;
            padding: 0;
        }

        a {
            color: #000;
        }

        li {
            list-style: none;
        }

        .banner {
            width: 100%;
            height: 200px;
            background: #caccc0;
        }

        .banner .title {
            margin: 0 auto;
            width: 80%;
            line-height: 100px;
            font-size: 40px;
            color: #fff;
        }

        .content {
            margin: 0 auto;
            width: 80%;
        }
    </style>
</head>

<body>
    <div class="banner">
        <div class="title">{{ website_title }}</div>
    </div>
    <div class="content">
        {{ article }}
    </div>
</body>

</html>

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ website_title }}</title>
    <style>
        html,body,div,p{
            margin: 0;
            padding: 0;
        }
        a{
            color: #000;
        }
        li{
            list-style: none;
        }
        .banner{
            width: 100%;
            height: 200px;
            background: #caccc0;
        }
        .banner .title{
            margin: 0 auto;
            width: 80%;
            line-height: 100px;
            font-size: 40px;
            color: #fff;
        }

        .content{
            margin: 0 auto;
            width: 80%;
        }
    </style>
</head>
<body>
    <div class="banner">
        <div class="title">{{ website_title }}</div>
    </div>
    <div class="content">
        <ul>
            <li></li>
        </ul>
        {% if blog_list %}
        <ul>
            {% for blog in blog_list %}
            <li>
                <a href="{% url 'blog:article' blog.id %}">{{ blog.article_title }} —— {{ blog.update_time }}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>暂无博文</p>
        {% endif %} 
    </div>
</body>
</html>